-- DUI ALCOHOL
-- DUI DRUGS
-- DUI ENDANGER CHILD
-- DUI MULTIPLE SUBS
-- UNDAGE POS/FURN ALCH
-- PED UNDER INFLUENCE
-- POSS OPEN CONT VEHIC
-- OPEN CONTAINERS
-- PUBLIC INTOXICATION
-- UNLAWFUL SALE OF ALC
-- INTOXICATION
-- PUBLIC DRUNKENNESS
-- PED WALKING ON ROAD
-- PUBLIC INDENCENCY
-- POSS OF MARIJ-1OZ-
-- POSS MARIJ W/INTENT
-- POSS/MANU/SELL/MARIJ
-- POSSESSION COCAINE
-- POSS COCAINE W/INTEN
-- DRUGS/ORIGINAL CO
-- TRAFFICKING IN DRUGS
-- SALE/DIST DANG DRUGS
-- POSS/USE DRUG OBJECT
-- DRUGS NEAR PRO/PARK
-- DRUGS NEAR SCH PROPE
-- OBTAIN DANG DRUG FRA
-- GUARD LINE DRUGS
-- POSS METHAMPHETAMINE
-- BUY/POSS III IV V SU
-- POSS/PUR SCH I II
-- POSS SCH II CONT SUB
-- POSS SCH III CONT.SU
-- POSS SCH IV CONT SUB
-- POSS I&II SUB W/INT
-- POSS III IV V W/INT
-- AGG SEXUAL BATTERY
-- AGGRAVATED BATTERY
-- BATTERY
-- BATTERY 3 OR MORE
-- SEXUAL BATTERY
-- SIM.BATT. PO/LE DOG
-- SIMP BATT FAMILY VIO
-- SIMPLE BATTERY
-- AFFRAY/FIGHTING PUB
-- AGG SODOMY W/FORCE
-- AGGRAVATED STALKING
-- VEH APPROACHING INTE
-- HEADLIGHTS
-- STOP & YIELD SIGNS
-- FAIL YIELD RIGHTAWAY
-- SPEEDING
-- IMPROPER DRIVING
-- NO PROOF INSURANCE
-- SUSPENDED LICENSE
-- TIRES/FAULTY
-- LIC/PROBATIONRY VIOL
-- IMPROPER PASSING
-- LICENSE REQUIRED
-- SAFETY BELTS PASS VE
-- BRAKE LIGHTS
-- HIT&RUN LEAVE SCENE
-- EXPIRED LICENSE
-- CENTER LANE VIOLATI
-- HIJACKING MOTOR VEHI
-- HIT&RUN/PARKED VEH.
-- SERIOUS INJURY VEHIC
-- UNSAFE EQUIPPED VEHI
-- OPER VEH APPRO EMERG
-- OBEY TRAFFIC CONTROL
-- WINDSHIELDS AND WIPE
-- WINDOW TINTING
-- U-TURN VIOLATION
-- TURNING MOVEMENTS
-- TOO FAST/CONDITIONS
-- TAIL LIGHT VIOL
-- SEAT BELTS REQUIRED
-- RIGHTOFWAY CROSSWALK
-- RECKLESS DRIVING
-- RACING ON HIGHWAYS
-- OPER UNREGISTERED VE
-- ONE WAY ROADWAY
-- OBEYING SIGNAL/SIGNS
-- LIGHTS REQUIRED
-- IMPROPER BACKING
-- HIT&RUN/ FIXED OBJ.
-- FOLLOWING TOO CLOSEL
-- FAILURE TO YIELD
-- FAILURE TO DIM LIGHT
-- DRIVE WRONG SIDE/ROA
-- IMP DISPLAY LI PLATE
-- IMPROPER TURNING
-- PLATE/CONCEAL/MISREP
-- SUS/REVOK REGISTRATI
-- EXPIRED TAG
-- PROBATION VIOL SUPCT
-- PROBATION VIOL STCRT
-- PROBATION VIOL MUNCT
-- PAROLE VIOLATION
-- SEX OFFEND VIOLATION
-- CRIMINAL TRESPASS
-- AGGRAVATED ASSAULT
-- SIMPLE ASSAULT
-- BURGLARY 1 DEGREE
-- BURGLARY 2 DEGREE
-- POSS BURGLARY TOOLS
-- ARMED ROBBERY
-- ROBBERY
-- PROBATION HOLD
-- OTHER AGENCY HOLD
-- FTC THEFT
-- THEFT BY CONVERSION
-- THEFT BY DECEPTION
-- THEFT BY RECEIVING
-- THEFT BY SHOPLIFTING
-- THEFT BY TAKING
-- THEFT OF LOST PROP
-- THEFT OF SERVICES
-- THEFT X RECEIV STOL.
-- CONTEMPT OF COURT
-- CONTEMPT OF MUN CT
-- CONTEMPT/SUP COURT
-- POSS/CARR CONCL WEAP
-- WEAPON SCHOOL ZONE
-- WEAPONS/SCHOOL PROP
-- DISC GUN/PROP ANOTH
-- DISC OF GUN NEAR HWY
-- POSS FIRARM COM CRIM
-- POSS GUN BY CONV FEL
-- FIREARM/COMM CRIME
-- GOOD BEHAVIOR BOND
-- VIOLATION OF BOND
-- BAIL JUMPING -MISD
-- DISORDERLY CONDUCT
-- RECKLESS CONDUCT (M)
-- UNLAWFUL CONDUCT 911
-- ABANDONMENT OF CHILD
-- CRUEL.CHILD-1ST DEG.
-- CRUEL CHILD -2ND DEG
-- CRUELTY CHILDREN-3RD
-- ENTERING AUTO
-- FAILURE TO APPEAR
-- RETURNED FOR COURT
-- VIOL.FAM.VIOL.ORDER
-- URINATE/DEFECATE PUB
-- FORGERY 1ST DEGREE
-- FORGERY 2ND DEGREE
-- FORGERY 3RD DEGREE F
-- FORGERY 4TH DEGREE
-- FINANCIAL ID FRAUD
-- FTC FRAUD
-- PRESCRIPTION FRAUD
-- BAD CHECKS
-- BAD CHK 1499 OR LESS
-- GIVING FALSE INFORMA
-- TERR THREATS/ACTS
-- TRAFFICKING PERSONS
-- MUN BENCH WARRANT
-- SUPCT ARREST WARRANT
-- POSS/MAKING FALSE ID
-- LIC/EXHIB ON DEMAND
-- LIC/FALSE NAME ON
-- LEARNERS PERMITS
-- KIDNAPPING
-- REPORT ACCID./INJURY
-- RIDING BICYCLE
-- TAMPERING W/EVIDENCE
-- CRIMINAL CONSPIRACY
-- OBSTRUCTION LEO
-- OBSTRUCTION 911
-- CRIMINAL DAMAGE 1DEG
-- CRIMINAL DAMAGE 2DEG
-- FALSE IMPRISONMENT
-- FALSE REPORT OF CRIM
-- FALSE SWEARING
-- FLEE/ATTEMP TO ELUDE
-- ENTERING/CROSSING RD
-- HAZING STUDENTS-MISD
-- LITTERING
-- LOITERING/PROWLING
-- FAL STATEMENT OFFICE
-- FUGITIVE/EXTRADITION
-- MURDER
-- HABITUAL VIOLATOR
-- HAB.VIOL W/REV.LIC.
-- IMPERON OFFIC/EMPLOY
-- EXPLOIT/ELDER-DISABL
-- FAIL REP ABUSE ELDR
-- LIMITS ON SOUND VOL
-- NOISE ORDINANCE VIOL
-- MOBILE PHONE/IMP USE
-- NON/RES/W/O LIC
-- OBSCENE LANG/HAR PHO
-- PEEPING TOM
-- INTER W/ TRAFFIC DEV
-- INTERFER WGOVT PROP
-- INTERFERENCE RANGER
-- CURFEW/NIGHT/STUDENT
-- RAPE
-- COMM FACILITY CONSUB
-- CRIM.ATTMPT COM.FEL
-- DISORDERLY HOUSE
-- EAVESDROPPING
-- EMERGING FROM ALLEY
-- FURTHER LIMITS L DRI
-- GIVING INMATES CONT.
-- HANDICAP PRKG VIOL.
-- LAYING DRAGS
-- HEADGEAR REQUIRED
-- RESTRICTED LIC
-- STALKING MISD
-- STOPPING STANDING
-- SUSP.LIC.-4TH OFFENS
-- REFUSAL TO PAY TAXI
SELECT * FROM booking_charge WHERE
	NOT charge_description="DUI ALCOHOL" AND
	NOT charge_description="DUI DRUGS" AND
	NOT charge_description="DUI ENDANGER CHILD" AND
	NOT charge_description="DUI MULTIPLE SUBS" AND
	NOT charge_description="UNDAGE POS/FURN ALCH" AND
	NOT charge_description="PED UNDER INFLUENCE" AND
	NOT charge_description="POSS OPEN CONT VEHIC" AND
NOT charge_description="OPEN CONTAINERS" AND
NOT charge_description="PUBLIC INTOXICATION" AND
NOT charge_description="UNLAWFUL SALE OF ALC" AND
NOT charge_description="INTOXICATION" AND
NOT charge_description="PUBLIC DRUNKENNESS" AND
NOT charge_description="PED WALKING ON ROAD" AND
NOT charge_description="PUBLIC INDENCENCY" AND

	NOT charge_description="POSS OF MARIJ-1OZ-" AND
	NOT charge_description="POSS MARIJ W/INTENT" AND
	NOT charge_description="POSS/MANU/SELL/MARIJ" AND

NOT charge_description="POSSESSION COCAINE" AND
NOT charge_description="POSS COCAINE W/INTEN" AND
NOT charge_description="DRUGS/ORIGINAL CO" AND
NOT charge_description="TRAFFICKING IN DRUGS" AND
NOT charge_description="SALE/DIST DANG DRUGS" AND
NOT charge_description="POSS/USE DRUG OBJECT" AND
NOT charge_description="DRUGS NEAR PRO/PARK" AND
NOT charge_description="DRUGS NEAR SCH PROPE" AND
NOT charge_description="OBTAIN DANG DRUG FRA" AND
NOT charge_description="GUARD LINE DRUGS" AND
NOT charge_description="POSS METHAMPHETAMINE" AND
NOT charge_description="" AND

NOT charge_description="BUY/POSS III IV V SU" AND
NOT charge_description="POSS/PUR SCH I II" AND
NOT charge_description="POSS SCH II CONT SUB" AND
NOT charge_description="POSS SCH III CONT.SU" AND
NOT charge_description="POSS SCH IV CONT SUB" AND
NOT charge_description="POSS I&II SUB W/INT" AND
NOT charge_description="POSS III IV V W/INT" AND

	NOT charge_description="AGG SEXUAL BATTERY" AND
	NOT charge_description="AGGRAVATED BATTERY" AND
	NOT charge_description="BATTERY" AND
	NOT charge_description="BATTERY 3 OR MORE" AND
	NOT charge_description="SEXUAL BATTERY" AND
	NOT charge_description="SIM.BATT. PO/LE DOG" AND
	NOT charge_description="SIMP BATT FAMILY VIO" AND
	NOT charge_description="SIMPLE BATTERY" AND
NOT charge_description="AFFRAY/FIGHTING PUB" AND
NOT charge_description="AGG SODOMY W/FORCE" AND
NOT charge_description="AGGRAVATED STALKING" AND



NOT charge_description="VEH APPROACHING INTE" AND
NOT charge_description="HEADLIGHTS" AND
NOT charge_description="STOP & YIELD SIGNS" AND
NOT charge_description="FAIL YIELD RIGHTAWAY" AND
NOT charge_description="SPEEDING" AND
NOT charge_description="IMPROPER DRIVING" AND
NOT charge_description="NO PROOF INSURANCE" AND
NOT charge_description="SUSPENDED LICENSE" AND
NOT charge_description="TIRES/FAULTY" AND
NOT charge_description="LIC/PROBATIONRY VIOL" AND
NOT charge_description="IMPROPER PASSING" AND
NOT charge_description="LICENSE REQUIRED" AND
NOT charge_description="SAFETY BELTS PASS VE" AND
NOT charge_description="BRAKE LIGHTS" AND
NOT charge_description="HIT&RUN LEAVE SCENE" AND
NOT charge_description="EXPIRED LICENSE" AND
NOT charge_description="CENTER LANE VIOLATI" AND
NOT charge_description="HIJACKING MOTOR VEHI" AND
NOT charge_description="HIT&RUN/PARKED VEH." AND
NOT charge_description="SERIOUS INJURY VEHIC" AND
NOT charge_description="UNSAFE EQUIPPED VEHI" AND
NOT charge_description="OPER VEH APPRO EMERG" AND
NOT charge_description="OBEY TRAFFIC CONTROL" AND
NOT charge_description="WINDSHIELDS AND WIPE" AND
NOT charge_description="WINDOW TINTING" AND
NOT charge_description="U-TURN VIOLATION" AND
NOT charge_description="TURNING MOVEMENTS" AND
NOT charge_description="TOO FAST/CONDITIONS" AND
NOT charge_description="TAIL LIGHT VIOL" AND
NOT charge_description="SEAT BELTS REQUIRED" AND
NOT charge_description="RIGHTOFWAY CROSSWALK" AND
NOT charge_description="RECKLESS DRIVING" AND
NOT charge_description="RACING ON HIGHWAYS" AND
NOT charge_description="OPER UNREGISTERED VE" AND
NOT charge_description="ONE WAY ROADWAY" AND
NOT charge_description="OBEYING SIGNAL/SIGNS" AND
NOT charge_description="LIGHTS REQUIRED" AND
NOT charge_description="IMPROPER BACKING" AND
NOT charge_description="HIT&RUN/ FIXED OBJ." AND
NOT charge_description="FOLLOWING TOO CLOSEL" AND
NOT charge_description="FAILURE TO YIELD" AND
NOT charge_description="FAILURE TO DIM LIGHT" AND
NOT charge_description="DRIVE WRONG SIDE/ROA" AND
NOT charge_description="IMP DISPLAY LI PLATE" AND
NOT charge_description="IMPROPER TURNING" AND
NOT charge_description="PLATE/CONCEAL/MISREP" AND
NOT charge_description="SUS/REVOK REGISTRATI" AND
NOT charge_description="EXPIRED TAG" AND
NOT charge_description="" AND
NOT charge_description="" AND

NOT charge_description="PROBATION VIOL SUPCT" AND
NOT charge_description="PROBATION VIOL STCRT" AND
NOT charge_description="PROBATION VIOL MUNCT" AND
NOT charge_description="PAROLE VIOLATION" AND
NOT charge_description="SEX OFFEND VIOLATION" AND

NOT charge_description="CRIMINAL TRESPASS" AND

NOT charge_description="AGGRAVATED ASSAULT" AND
NOT charge_description="SIMPLE ASSAULT" AND

NOT charge_description="BURGLARY 1 DEGREE" AND
NOT charge_description="BURGLARY 2 DEGREE" AND
NOT charge_description="POSS BURGLARY TOOLS" AND

NOT charge_description="ARMED ROBBERY" AND
NOT charge_description="ROBBERY" AND

NOT charge_description="PROBATION HOLD" AND
NOT charge_description="OTHER AGENCY HOLD" AND

NOT charge_description="FTC THEFT" AND
NOT charge_description="THEFT BY CONVERSION" AND
NOT charge_description="THEFT BY DECEPTION" AND
NOT charge_description="THEFT BY RECEIVING" AND
NOT charge_description="THEFT BY SHOPLIFTING" AND
NOT charge_description="THEFT BY TAKING" AND
NOT charge_description="THEFT OF LOST PROP" AND
NOT charge_description="THEFT OF SERVICES" AND
NOT charge_description="THEFT X RECEIV STOL." AND


NOT charge_description="CONTEMPT OF COURT" AND
NOT charge_description="CONTEMPT OF MUN CT" AND
NOT charge_description="CONTEMPT/SUP COURT" AND

NOT charge_description="POSS/CARR CONCL WEAP" AND
NOT charge_description="WEAPON SCHOOL ZONE" AND
NOT charge_description="WEAPONS/SCHOOL PROP" AND
NOT charge_description="DISC GUN/PROP ANOTH" AND
NOT charge_description="DISC OF GUN NEAR HWY" AND
NOT charge_description="POSS FIRARM COM CRIM" AND
NOT charge_description="POSS GUN BY CONV FEL" AND
NOT charge_description="FIREARM/COMM CRIME" AND
NOT charge_description="" AND

NOT charge_description="GOOD BEHAVIOR BOND" AND
NOT charge_description="VIOLATION OF BOND" AND
NOT charge_description="BAIL JUMPING -MISD" AND

NOT charge_description="DISORDERLY CONDUCT" AND
NOT charge_description="RECKLESS CONDUCT (M)" AND
NOT charge_description="UNLAWFUL CONDUCT 911" AND

NOT charge_description="ABANDONMENT OF CHILD" AND
NOT charge_description="CRUEL.CHILD-1ST DEG." AND
NOT charge_description="CRUEL CHILD -2ND DEG" AND
NOT charge_description="CRUELTY CHILDREN-3RD" AND

NOT charge_description="ENTERING AUTO" AND

NOT charge_description="FAILURE TO APPEAR" AND
NOT charge_description="RETURNED FOR COURT" AND

NOT charge_description="VIOL.FAM.VIOL.ORDER" AND

NOT charge_description="URINATE/DEFECATE PUB" AND


NOT charge_description="FORGERY 1ST DEGREE" AND
NOT charge_description="FORGERY 2ND DEGREE" AND
NOT charge_description="FORGERY 3RD DEGREE F" AND
NOT charge_description="FORGERY 4TH DEGREE" AND

NOT charge_description="FINANCIAL ID FRAUD" AND
NOT charge_description="FTC FRAUD" AND
NOT charge_description="PRESCRIPTION FRAUD" AND

NOT charge_description="BAD CHECKS" AND
NOT charge_description="BAD CHK 1499 OR LESS" AND

NOT charge_description="GIVING FALSE INFORMA" AND

NOT charge_description="TERR THREATS/ACTS" AND

NOT charge_description="TRAFFICKING PERSONS" AND

NOT charge_description="MUN BENCH WARRANT" AND
NOT charge_description="SUPCT ARREST WARRANT" AND

NOT charge_description="POSS/MAKING FALSE ID" AND
NOT charge_description="LIC/EXHIB ON DEMAND" AND
NOT charge_description="LIC/FALSE NAME ON" AND
NOT charge_description="LEARNERS PERMITS" AND
NOT charge_description="" AND
NOT charge_description="" AND

NOT charge_description="KIDNAPPING" AND

NOT charge_description="REPORT ACCID./INJURY" AND

NOT charge_description="RIDING BICYCLE" AND

NOT charge_description="TAMPERING W/EVIDENCE" AND

NOT charge_description="CRIMINAL CONSPIRACY" AND

NOT charge_description="OBSTRUCTION LEO" AND
NOT charge_description="OBSTRUCTION 911" AND


NOT charge_description="CRIMINAL DAMAGE 1DEG" AND
NOT charge_description="CRIMINAL DAMAGE 2DEG" AND


NOT charge_description="FALSE IMPRISONMENT" AND
NOT charge_description="FALSE REPORT OF CRIM" AND
NOT charge_description="FALSE SWEARING" AND

NOT charge_description="FLEE/ATTEMP TO ELUDE" AND

NOT charge_description="ENTERING/CROSSING RD" AND

NOT charge_description="HAZING STUDENTS-MISD" AND

NOT charge_description="LITTERING" AND
NOT charge_description="LOITERING/PROWLING" AND


NOT charge_description="FAL STATEMENT OFFICE" AND
NOT charge_description="FUGITIVE/EXTRADITION" AND

NOT charge_description="MURDER" AND

NOT charge_description="HABITUAL VIOLATOR" AND
NOT charge_description="HAB.VIOL W/REV.LIC." AND

NOT charge_description="IMPERON OFFIC/EMPLOY" AND

NOT charge_description="EXPLOIT/ELDER-DISABL" AND
NOT charge_description="FAIL REP ABUSE ELDR" AND


NOT charge_description="LIMITS ON SOUND VOL" AND
NOT charge_description="NOISE ORDINANCE VIOL" AND

NOT charge_description="MOBILE PHONE/IMP USE" AND

NOT charge_description="NON/RES/W/O LIC" AND

NOT charge_description="OBSCENE LANG/HAR PHO" AND

NOT charge_description="PEEPING TOM" AND


NOT charge_description="INTER W/ TRAFFIC DEV" AND
NOT charge_description="INTERFER WGOVT PROP" AND
NOT charge_description="INTERFERENCE RANGER" AND

NOT charge_description="CURFEW/NIGHT/STUDENT" AND

NOT charge_description="RAPE" AND



NOT charge_description="COMM FACILITY CONSUB" AND
NOT charge_description="CRIM.ATTMPT COM.FEL" AND
NOT charge_description="DISORDERLY HOUSE" AND
NOT charge_description="EAVESDROPPING" AND

NOT charge_description="EMERGING FROM ALLEY" AND
NOT charge_description="FURTHER LIMITS L DRI" AND
NOT charge_description="GIVING INMATES CONT." AND
NOT charge_description="HANDICAP PRKG VIOL." AND
NOT charge_description="LAYING DRAGS" AND
NOT charge_description="HEADGEAR REQUIRED" AND
NOT charge_description="RESTRICTED LIC" AND
NOT charge_description="STALKING MISD" AND
NOT charge_description="STOPPING STANDING" AND
NOT charge_description="SUSP.LIC.-4TH OFFENS" AND
NOT charge_description="REFUSAL TO PAY TAXI" AND
NOT charge_description="" AND
NOT charge_description="" AND
NOT charge_description="" AND

charge_description LIKE '%%';